import moment from 'moment';

export const VALID_EMAIL = "test@test.com";
export const VALID_PASSWORD = "test123";

export const PropertyTypes = [
  "Apartment/Condo",
  "Single Family",
  "Multi-Family",
  "Townhouse",
  "Other",
];

export const Tenants = [
  {
    id: 1,
    properties: [2],
    name: "Elizabeth Olsen",
    phone: "1234567890",
    email: "eliza@gmail.com",
    leaseType: "monthly",
    leaseStartDate: "1/12/2021",
    leaseEndDate: null,
    securityDeposit: 500,
    recurringPaymentType: "Monthly",
    totalOccupants: 1,
    notes: "",
    rent: 1000,
  },
  {
    id: 2,
    properties: [2],
    name: "Lady Gaga",
    phone: "1234567890",
    email: "eliza@gmail.com",
    leaseType: "monthly",
    leaseStartDate: "1/12/2021",
    leaseEndDate: null,
    securityDeposit: 500,
    recurringPaymentType: "Monthly",
    totalOccupants: 1,
    notes: "",
    rent: 1000,
  },
  {
    id: 3,
    properties: [2],
    name: "Ed Sheeran",
    phone: "1234567890",
    email: "eliza@gmail.com",
    leaseType: "monthly",
    leaseStartDate: "1/12/2021",
    leaseEndDate: null,
    securityDeposit: 500,
    recurringPaymentType: "Monthly",
    totalOccupants: 1,
    notes: "",
    rent: 1000,
  },
  {
    id: 4,
    properties: [1],
    name: "Sam Smith",
    phone: "1234567890",
    email: "eliza@gmail.com",
    leaseType: "monthly",
    leaseStartDate: "1/12/2021",
    leaseEndDate: null,
    securityDeposit: 500,
    recurringPaymentType: "Monthly",
    totalOccupants: 1,
    notes: "",
    rent: 1000,
  },
  {
    id: 5,
    properties: [1],
    name: "Ashton Kutcher",
    phone: "1234567890",
    email: "eliza@gmail.com",
    leaseType: "monthly",
    leaseStartDate: "1/12/2021",
    leaseEndDate: null,
    securityDeposit: 500,
    recurringPaymentType: "Monthly",
    totalOccupants: 1,
    notes: "",
    rent: 1000,
  },
  {
    id: 6,
    properties: [1],
    name: "Ashton Kutcher",
    phone: "1234567890",
    email: "eliza@gmail.com",
    leaseType: "monthly",
    leaseStartDate: moment("11/11/2011"),
    leaseEndDate: null,
    securityDeposit: 500,
    recurringPaymentType: "Monthly",
    totalOccupants: 1,
    notes: "",
    rent: 1000,
  },
  {
    id: 7,
    properties: [1],
    name: "Ashton Kutcher",
    phone: "1234567890",
    email: "eliza@gmail.com",
    leaseType: "monthly",
    leaseStartDate: moment("10/11/2018"),
    leaseEndDate: null,
    securityDeposit: 500,
    recurringPaymentType: "Monthly",
    totalOccupants: 1,
    notes: "",
    rent: 1000,
  },
  {
    id: 8,
    properties: [1],
    name: "Ashton Kutcher",
    phone: "1234567890",
    email: "eliza@gmail.com",
    leaseType: "monthly",
    leaseStartDate: moment("4/18/2019"),
    leaseEndDate: null,
    securityDeposit: 500,
    recurringPaymentType: "Monthly",
    totalOccupants: 1,
    notes: "",
    rent: 1000,
  },
  {
    id: 9,
    properties: [1],
    name: "Ashton Kutcher",
    phone: "1234567890",
    email: "eliza@gmail.com",
    leaseType: "monthly",
    leaseStartDate: moment("2/12/2021"),
    leaseEndDate: null,
    securityDeposit: 500,
    recurringPaymentType: "Monthly",
    totalOccupants: 1,
    notes: "",
    rent: 1000,
  },
  {
    id: 10,
    properties: [1],
    name: "Ashton Kutcher",
    phone: "1234567890",
    email: "eliza@gmail.com",
    leaseType: "monthly",
    leaseStartDate: moment("1/12/2020"),
    leaseEndDate: null,
    securityDeposit: 500,
    recurringPaymentType: "Monthly",
    totalOccupants: 1,
    notes: "",
    rent: 1000,
  },
];

export const Properties = [
  {
    id: 1,
    propertyName: "My Awesome House Rental",
    propertyAddress: "1234 Liberty Avenue",
    notes: "",
    tenants: [4, 5],
    image: null,
    unitType: PropertyTypes[1],
    income: 1860,
    expenses: 500,
    color: "#F2CC8F",
  },
  {
    id: 2,
    propertyName: "My Awesome Apartment Rental",
    propertyAddress: "567 Raven Court",
    notes: "",
    tenants: [1, 2, 3],
    image: "",
    unitType: PropertyTypes[0],
    income: 1000,
    expenses: 500,
    color: "#81B29A",
  },
  {
    id: 3,
    propertyName: "My Awesome Duplex",
    propertyAddress: "8793 Sudarland Blvd.",
    notes: "",
    tenants: [],
    image: "",
    unitType: PropertyTypes[2],
    income: 0,
    expenses: 2500,
    color: "#E29578",
  },
  {
    id: 4,
    propertyName: "My Awesome Townhouse",
    propertyAddress: "11888 Prince William St.",
    notes: "",
    tenants: [7, 8, 9, 10],
    image: "",
    unitType: PropertyTypes[3],
    income: 1000,
    expenses: 2000,
    color: "#8ECAE6",
  },
];

export const User = {
  email: VALID_EMAIL,
  password: VALID_PASSWORD,
  phone: "1234567890",
  properties: Properties,
  firstName: "Albert",
};
